export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_MONSTERS_STARTED = 'REQUEST_MONSTERS_STARTED';
export const REQUEST_MONSTERS_COMPLETED = 'REQUEST_MONSTERS_COMPLETED';
export const REQUEST_MONSTER_ERROR = 'REQUEST_MONSTERS_ERROR';